#put the docker-network info directly inside this file to be respect the subject's structure example

#je pense qu'ici iront les commandes type :
# sudo docker build -t nginx_img srcs/requirements/NGINX
# sudo docker run -d -p 443:443 nginx_img
# OR
# sudo docker run -it nginx

# sudo docker build -t mariadb_img srcs/requirements/MariaDB
# sudo docker run -d -p 3306:3306  mariadb_img
# OR
# sudo docker run -it mariadb

# sudo docker build -t wordpress_img srcs/requirements/WordPress




# version: ‘3’

# services:
# 	mariadb:
# 	container_name: mariadb			# Le nom du container, oui vraiment.
# 	networks:
# 	- inception            			# à quel network il appartient
# 	build: 
# 	context: requirements/MariaDB 	# ou se trouve son Dockerfile
# 	dockerfile: Dockerfile			# le nom du Dockerfile ?!
# 	env_file: .env                  # le fichier d'environnement pour transmettre les variables
# 	volumes:                        # Voir plus bas
# 	- mariadb:/var/lib/mysql
# 	restart: unless-stopped         # redémarre tant qu'il n'est pas stoppé 
# 	expose:                         # le port à exposer
# 	- "3306"