#put the docker-network info directly inside this file to be respect the subject's structure example

#je pense qu'ici iront les commandes type :
sudo docker build -t nginx_img srcs/requirements/NGINX
sudo docker run -d -p 443:443 nginx_img
OR
sudo docker run -it nginx

sudo docker build -t mariadb_img srcs/requirements/MariaDB
sudo docker run -d -p 3306:3306  mariadb_img
OR
sudo docker run -it mariadb